package dev.mcodex.RNSensitiveInfo.utils;

public interface AppConstants {

    String DIALOG_FRAGMENT_TAG = "authFragment";

    // error codes
    String KM_ERROR_KEY_USER_NOT_AUTHENTICATED = "KM_ERROR_KEY_USER_NOT_AUTHENTICATED";
    String KM_UNABLE_TO_DECRYPT_KEY = "KM_UNABLE_TO_DECRYPT_KEY";
    String FINGERPRINT_AUTHENTICATION_HELP = "FINGERPRINT_AUTHENTICATION_HELP";
    String E_AUTHENTICATION_NOT_RECOGNIZED = "E_AUTHENTICATION_NOT_RECOGNIZED";
    String E_AUTHENTICATION_CANCELLED = "E_AUTHENTICATION_CANCELLED";
    String E_BIOMETRIC_NOT_SUPPORTED = "E_BIOMETRIC_NOT_SUPPORTED";
    String E_INIT_FAILURE = "E_INIT_FAILURE";
    String E_BIOMETRICS_INVALIDATED = "E_BIOMETRICS_INVALIDATED";
    String E_SECURITY_VIOLATION = "E_SECURITY_VIOLATION";
}